name: bk-tutorial
channels:
  - conda-forge
dependencies:
  - black
  - bokeh>=3.0.0
  - firefox
  - flake8
  - geckodriver
  - geojson
  - geopandas
  - nbqa
  - notebook
  - pandas
  - pre-commit
  - pyshp
  - python>=3.10
